// This file is auto-generated by scripts/generateLiveVideosList.js
export const videos = [
  {
    "name": "Балада про зайшлого чоловіка",
    "src": "live-videos/Балада про зайшлого чоловіка.mp4"
  },
  {
    "name": "Гранітні обеліски",
    "src": "live-videos/Гранітні обеліски.mp4"
  },
  {
    "name": "Де зараз ви кати мого народу",
    "src": "live-videos/Де зараз ви кати мого народу.mp4"
  },
  {
    "name": "Задивляюсь у твої зіниці",
    "src": "live-videos/Задивляюсь у твої зіниці.mp4"
  },
  {
    "name": "Злодій",
    "src": "live-videos/Злодій.mp4"
  },
  {
    "name": "Лебеді материнства",
    "src": "live-videos/Лебеді материнства.mp4"
  },
  {
    "name": "Може так і треба",
    "src": "live-videos/Може так і треба.mp4"
  },
  {
    "name": "Монархи",
    "src": "live-videos/Монархи.mp4"
  },
  {
    "name": "Некролог кукурудзяному качанові, що згнив на заготпункті",
    "src": "live-videos/Некролог кукурудзяному качанові, що згнив на заготпункті.mp4"
  },
  {
    "name": "Одинока матір",
    "src": "live-videos/Одинока матір.mp4"
  },
  {
    "name": "Перехожий",
    "src": "live-videos/Перехожий.mp4"
  },
  {
    "name": "Світ який",
    "src": "live-videos/Світ який.mp4"
  },
  {
    "name": "Суд",
    "src": "live-videos/Суд.mp4"
  },
  {
    "name": "Ти знаєш що ти людина",
    "src": "live-videos/Ти знаєш що ти людина.mp4"
  },
  {
    "name": "Я (В.Симоненко)",
    "src": "live-videos/Я (В.Симоненко).mp4"
  }
];
export default videos;
