#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const videosDir = path.join(process.cwd(), "videos");
const outFile = path.join(process.cwd(), "js-partials", "videosData.js");

function generate() {
  if (!fs.existsSync(videosDir)) {
    console.error("videos directory not found:", videosDir);
    process.exit(1);
  }
  const files = fs.readdirSync(videosDir).filter((f) => /\.mp4$/i.test(f));
  const items = files.map((f) => {
    const name = path.basename(f, path.extname(f)).replace(/_/g, " ");
    const src = ["videos", f].join("/");
    return { name, src };
  });
  const content = `// This file is auto-generated by scripts/generateVideosList.js\nexport const videos = ${JSON.stringify(
    items,
    null,
    2
  )};\nexport default videos;\n`;
  fs.writeFileSync(outFile, content, "utf8");
  console.log("Wrote", outFile, "with", items.length, "items");
}

generate();
